micronaut:
  application:
    name: analytics
    instance:
      id: ${random.shortuuid}
  config-client:
    enabled: true
db:
  name: 'analytics'
  collection: 'analytics'
netty:
  default:
    allocator:
      max-order: 3
endpoints:
  health:
    enabled: true
    sensitive: false