micronaut:
  security:
    enabled: false
  config-client:
    enabled: false
  server:
    port: 8080
consul:
  client:
    registration:
      enabled: false
mongodb:
  uri: 'mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/db'
db:
  name: 'analytics'
  collection: 'analytics'